data.tf

https://tools.hmcts.net/jira/browse/LAU-124
Add CFT app permissions to allow apps to see infrastructure.
```
[ ] Yes
[x] No
```

LAU-124: Updated to add aks cft app permissions.

---

.gitignore
data.tf
main.tf
perftest.tfvars
provider.tf
state.tf

https://tools.hmcts.net/jira/browse/LAU-124
Update to permissions again.
```
[ ] Yes
[x] No
```

LAU-124 Update to permissions again.

---

application-insights.tf

https://tools.hmcts.net/jira/browse/LAU-278
Update Azure Resources (via Terraform) with Resource Tags
```
[ ] Yes
[x] No
```

LAU-278 Update Azure Resources (via Terraform) with Resource Tags

---

alerts.tf

Update evaluation time

---

alerts.tf

Change alarm name

---

alerts.tf
outputs.tf

Disable all alerts.tf

---

data.tf

Update aks network name.

---

alerts.tf
outputs.tf

Unable case disposer alert

---

aat.tfvars
alerts.tf
prod.tfvars

https://tools.hmcts.net/jira/browse/LAU-478
Add case disposer fail to delete case alert
```
[ ] Yes
[x] No
```

Update case disposer frequency check and unable it in prod.

---

aat.tfvars

Disable alerts on aat.

---

aat.tfvars
alerts.tf

Rename alerts to force terraform to create new prod alert.

---

alerts.tf

https://tools.hmcts.net/jira/browse/LAU-478
Update shortname.
```
[ ] Yes
[x] No
```

LAU-478: update action group short name.

---

alerts.tf

Update prod alert for testing.

---

alerts.tf

Revert prod alert.

---

app-insights.tf
data.tf
state.tf

https://tools.hmcts.net/jira/browse/LAU-589
This change is to add AppInsight key in key vault
```
[ ] Yes
[x] No
```

LAU-589  Adding appInsight key

---

alerts.tf

Change alert location
Change alert location
```
[ ] Yes
[x] No
```

Change alert location

---

alerts.tf

Change alert name

---

aat.tfvars
alerts.tf
data.tf
demo.tfvars
ithc.tfvars
main.tf
perftest.tfvars
prod.tfvars
provider.tf
variables.tf

https://tools.hmcts.net/jira/browse/LAU-593
case-disposer-deletion summary alert
will test this on demo

LAU-593 case disposer summary alerts

---

alerts.tf
demo.tfvars
variables.tf

https://tools.hmcts.net/jira/browse/LAU-593
Running alert query on demo on every 15 minutes
test will be done on demo

LAU-593 running alert query on demo every 15 minutes

---

demo.tfvars
prod.tfvars

https://tools.hmcts.net/jira/browse/LAU-593
enabling on prod
after testing on demo enabling on prod

LAU-593 enabling on prod

---

alerts.tf

https://tools.hmcts.net/jira/projects/LAU/issues/LAU-1123
Run failed deletions alerts check once a day

LAU-1123 run failed alerts monitoring once a day

---

provider.tf

Remove skip_provider_registration and let terraform choose default one automatically
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

LAU-1250 Remove skip_provider_registration
